# Generated by Django 4.2.5 on 2023-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('battle_tag', models.CharField(blank=True, max_length=20, null=True)),
                ('phonenum', models.CharField(blank=True, max_length=15, null=True)),
                ('safe_um_user', models.CharField(blank=True, max_length=30, null=True)),
                ('safe_um_pass', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('channelid', models.CharField(blank=True, max_length=255, null=True)),
                ('finished', models.BooleanField()),
                ('taken', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=12, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=12, null=True)),
                ('email_password', models.CharField(blank=True, max_length=40, null=True)),
                ('finished_date', models.CharField(blank=True, max_length=12, null=True)),
                ('hex_secret_key', models.CharField(blank=True, max_length=41, null=True)),
                ('serial', models.CharField(blank=True, max_length=14, null=True)),
                ('restore_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('paymentdate', models.CharField(blank=True, db_column='paymentDate', max_length=20, null=True)),
                ('paymentnum', models.CharField(db_column='paymentNum', max_length=15)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('channelid', models.CharField(blank=True, max_length=255, null=True)),
                ('payed', models.BooleanField()),
                ('confirmed', models.BooleanField()),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
